DROP DATABASE IF EXISTS RH;
CREATE DATABASE IF NOT EXISTS RH;
USE RH;

CREATE TABLE IF NOT EXISTS REGIAO (
    ID_REGIAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_REGIAO VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS PAIS (
    ID_PAIS CHAR(2) NOT NULL PRIMARY KEY,
    NOME_PAIS VARCHAR(40),
    ID_REGIAO INT,
    FOREIGN KEY (ID_REGIAO)
        REFERENCES REGIAO (ID_REGIAO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LOCALIZACAO (
    ID_LOCALIZACAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ENDERECO VARCHAR(40),
    CEP VARCHAR(12),
    CIDADE VARCHAR(30),
    ESTADO VARCHAR(25),
    ID_PAIS CHAR(2),
    FOREIGN KEY (ID_PAIS)
        REFERENCES PAIS (ID_PAIS)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FUNCAO (
    ID_FUNCAO VARCHAR(10) NOT NULL PRIMARY KEY,
    TITULO_FUNCAO VARCHAR(35),
    SALARIO_MINIMO FLOAT(22 , 2 ),
    SALARIO_MAXIMO FLOAT(22 , 2 )
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
    ID_DEPARTAMENTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_DEPARTAMENTO VARCHAR(30),
    ID_GERENTE INT,
    ID_LOCALIZACAO INT,
    FOREIGN KEY (ID_LOCALIZACAO)
        REFERENCES LOCALIZACAO (ID_LOCALIZACAO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
    ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(20),
    SOBRENOME VARCHAR(25),
    EMAIL VARCHAR(25),
    TELEFONE VARCHAR(20),
    DATA_CONTRATACAO DATE,
    ID_FUNCAO VARCHAR(10),
    SALARIO FLOAT(22 , 2 ),
    COMISSAO INT,
    ID_GERENTE INT,
    ID_DEPARTAMENTO INT,
    FOREIGN KEY (ID_GERENTE)
        REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_DEPARTAMENTO)
        REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_FUNCAO)
        REFERENCES FUNCAO (ID_FUNCAO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

        
CREATE TABLE IF NOT EXISTS HISTORICO_FUNCOES (
    ID_FUNCIONARIO INT NOT NULL,
    DATA_INICIAL DATE,
    DATA_FINAL DATE,
    ID_FUNCAO VARCHAR(10),
    ID_DEPARTAMENTO INT,
    PRIMARY KEY (ID_FUNCIONARIO , DATA_INICIAL),
    FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_FUNCAO)
        REFERENCES FUNCAO (ID_FUNCAO)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_DEPARTAMENTO)
        REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
        ON UPDATE CASCADE ON DELETE CASCADE
);


ALTER TABLE DEPARTAMENTO 
	ADD FOREIGN KEY (ID_GERENTE) 
		REFERENCES FUNCIONARIO (ID_FUNCIONARIO) ON UPDATE CASCADE ON DELETE CASCADE;